Sourcecode/CoreNewRequirment/CoreNewRequirment/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using CoreNewRequirment.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace CoreNewRequirment.Controllers
{
    public class TestController : Controller
    {
        private string baseURI = string.Empty; 
        private string token = string.Empty;

        private IConfiguration _config;
        public TestController(IConfiguration config)
        {
            _config = config;
            this.baseURI = _config["ApiBaseUrl"];
        }

        #region ManageTest
        public IActionResult TestDetail()
        {
            return View();
        }
        /// <summary>
        ///Method for getting list of test.
        /// </summary>
        /// <returns>Test list</returns>
        [HttpGet]
        public IActionResult Index()
        {
            this.token = HttpContext.Session.GetString("token");
            List<GetAllTest> lstGetAllTest = new List<GetAllTest>();
            try
            {
                using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + this.token);
                    var responseTask = client.GetAsync(baseURI + "/Test/GetAllTest");

                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {

                        var readTask = result.Content.ReadAsAsync<GetAllTest[]>();
                        readTask.Wait();

                        var test = readTask.Result;
                        foreach (GetAllTest data in test)
                        {
                            lstGetAllTest.Add(data);
                        }
                    }
                }
                ViewBag.FirstName = HttpContext.Session.GetString("FirstName");
                ViewBag.LastName = HttpContext.Session.GetString("LastName");
                return View("TestDetail", lstGetAllTest);
            }
            catch (Exception)
            {
                return View("TestDetail", lstGetAllTest);
            }
        }
        /// <summary>
        /// Method for creatiion of test.
        /// </summary>
        /// <param name="test">test type,test date</param>
        /// <returns>Status message</returns>
        [HttpGet]
        public string CreateTest(Test test)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    this.token = HttpContext.Session.GetString("token");
                    var stringContent = new StringContent(JsonConvert.SerializeObject(test), Encoding.UTF8, "application/json");
                    var token = HttpContext.Session.GetString("token");
                    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + this.token);
                    var responseTask = client.PostAsync(baseURI + "/Test/CreateTest", stringContent);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return "Success";
                    }
                }
                return "";
            }
            catch (Exception)
            {
                return "Failure";
            }
        }
        /// <summary>
        /// Method for removing test.
        /// </summary>
        /// <param name="testId">test id</param>
        /// <returns>Status message</returns>
        [HttpGet]
        public string DeleteTest(long testId)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    this.token = HttpContext.Session.GetString("token");
                    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + this.token);
                    var responseTask = client.DeleteAsync(baseURI + "/Test/DeleteTest?testId=" + testId);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();
                        return readTask.Result.ToString();
                    }
                }
                return "Sucess";
            }
            catch (Exception)
            {
                return "Failure";
            }
        }
        #endregion

        #region ManageAthlete
        /// <summary>
        /// Method for getting result of athlete
        /// </summary>
        /// <returns>Result list of athlete</returns>
        [HttpGet]
        public IActionResult GetAthleteResultList()
        {
            List<AthleteResult> lstAthleteResult = new List<AthleteResult>();
            try
            {
                using (var client = new HttpClient())
                {
                    this.token = HttpContext.Session.GetString("token");
                    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + this.token);
                    var responseTask = client.GetAsync(baseURI + "/Athlete/GetAthleteResult?userId=" + HttpContext.Session.GetInt32("UserId"));
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {

                        var readTask = result.Content.ReadAsAsync<AthleteResult[]>();
                        readTask.Wait();

                        var test = readTask.Result;
                        foreach (AthleteResult data in test)
                        {
                            if(data.TestName.Contains("Sprint"))
                            {
                                
                            }
                            lstAthleteResult.Add(data);
                        }
                    }
                }
                ViewBag.FirstName = HttpContext.Session.GetString("FirstName");
                ViewBag.LastName = HttpContext.Session.GetString("LastName");
                return View(lstAthleteResult);
            }
            catch(Exception)
            {
                ViewBag.FirstName = HttpContext.Session.GetString("FirstName");
                ViewBag.LastName = HttpContext.Session.GetString("LastName");
                return View(lstAthleteResult);
            }
        }

        /// <summary>
        /// Method for getting athlete list for add and update of athlete in test
        /// </summary>
        /// <param name="auFlag">Flag for Add/Update operation</param>
        /// <param name="testId">test id</param>
        /// <returns>Athlete list for test</returns>
        [HttpGet]
        public List<GetTestAthlete> GetAthleteForTest(string auFlag, long testId)
        {
            List<GetTestAthlete> lstGetTestAthlete = new List<GetTestAthlete>();
            try
            {
                using (var client = new HttpClient())
                {
                    this.token = HttpContext.Session.GetString("token");
                    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + this.token);
                    var responseTask = client.GetAsync(baseURI + "/Athlete/GetAthleteListForAddNUpdate?auFlag=" + auFlag + "&testId=" + testId);

                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<GetTestAthlete[]>();
                        readTask.Wait();
                        var data = readTask.Result;
                        foreach (GetTestAthlete testAthlete in data)
                        {
                            lstGetTestAthlete.Add(testAthlete);
                        }
                    }
                }
                return lstGetTestAthlete;
            }
            catch (Exception)
            {
                return lstGetTestAthlete;
            }
        }

        /// <summary>
        /// Method for updating athlete score in test
        /// </summary>
        /// <param name="athleteTest">test id,user id and updated score</param>
        /// <returns>Status message</returns>
        [HttpPost]
        public string UpdateAthleteInTest(AthleteTest athleteTest)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    this.token = HttpContext.Session.GetString("token");
                    var stringContent = new StringContent(JsonConvert.SerializeObject(athleteTest), Encoding.UTF8, "application/json");
                    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + this.token);
                    var responseTask = client.PostAsync(baseURI + "/Athlete/UpdateAthleteInTest", stringContent);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();
                        return readTask.Result;
                    }
                    else
                    {
                        return "Failure";
                    }
                }

Sourcecode/CoreNewRequirment/CoreNewRequirment/Views/Test/GetAthleteResultList.cshtml
@model IEnumerable<CoreNewRequirment.Models.AthleteResult>
<script>
    function logout() {
       window.location.href= '@Url.Action("Logout", "Home")'
    }
</script>
<div  style="float:right">
    welcome @ViewBag.FirstName @ViewBag.LastName <button class="btn btn-info" onclick="logout()">Logout</button>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TestName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Score)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TestName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Score)
                @if (item.TestName.Contains("Sprint"))
                {<span>seconds</span>}
                @if (item.TestName.Contains("Cooper"))
                {<span> meters</span>}
            </td>
        </tr>
}
    </tbody>
</table>

Sourcecode/CoreNewRequirment/CoreNewRequirment/Views/Test/TestDetail.cshtml
@using CoreNewRequirment.Models;
@model IEnumerable<GetAllTest>

<script>
    $(function () {
        $('#Date').datepicker();
    })

    function CreateTest() {
        $("#CreateTest").modal()
    }
    function SaveTest() {
        if ($('#Date').val().trim() != '') {
            $.ajax({
                url: "@Url.Action("IsTestExist", "Test")",
                data: { "TestMasterId": $('#TestType').val(), "Date": $('#Date').val() },
                success: function (data) {
                    if (data == 'notfound') {
                        $.ajax({
                            url: "@Url.Action("CreateTest", "Test")",
                            data: { "TestMasterId": $('#TestType').val(), "Date": $('#Date').val() },
                            success: function () {
                                window.location.href = "@Url.Action("Index", "Test")"
                            },
                            error: function () {
                                alert("Something went wrong.")
                            }
                        });
                    }
                    else {
                        if (confirm("Test for same day is already do you want to add other one?")) {
                            $.ajax({
                                url: "@Url.Action("CreateTest", "Test")",
                                data: { "TestMasterId": $('#TestType').val(), "Date": $('#Date').val() },
                                success: function () {
                                    window.location.href = "@Url.Action("Index", "Test")"
                                },
                                error: function () {
                                    alert("Something went wrong.")
                                }
                            });
                        }
                    }
                },
                error: function () {
                    alert("Something went wrong.")
                }
            });

            $("#CreateTest").modal("hide")
        }
        else {
            $('#formValidationMessage').show()
        }
    }
    function logout() {
        window.location.href= '@Url.Action("Logout", "Home")'
    }
    function redirect(redirectUrl) {
        window.location.href = redirectUrl;
    }
</script>
<div  style="float:right">
    welcome @ViewBag.FirstName @ViewBag.LastName <button class="btn btn-info" onclick="logout()" >Logout</button>
</div>
<div id="CreateTest" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Create New Test</h4>
            </div>
            <div class="modal-body" style="min-height:90px">
                <div class="col-md-12">
                    <label class="col-md-3">Type</label>
                    <select id="TestType" class="col-md-9">
                        <option value="1">Cooper Test</option>
                        <option value="2">Sprint Test</option>
                    </select>
                </div>
                <div class="col-md-12">
                    <label class="col-md-3">Date</label>
                    <input type="text" id="Date" class="col-md-9" autocomplete="off" />
                    <div id="formValidationMessage" style="color:red;display:none">Date is required.</div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="SaveTest()" class="btn btn-default">Create</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<center>
    <div class="">
        <button type="button" class="btn btn-info" onclick="CreateTest()">CREATE NEW TEST</button>
    </div>
</center>
<div style="width: 100%;margin-top:10px;">
    <div class="table-responsive" style="width: 98%;">
        <table class="table  table-bordered  table-striped  tblFloor" cellspacing="0">
            <thead>
                <tr class="">
                    <th class="tblheader">Date</th>
                    <th class="tblheader">No of Participants</th>
                    <th class="cls_action tblheader">TestType</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="" class="" onclick="redirect('GetTestAthlete?testid=@item.TestId&testname=@item.Name&date=@item.Date&testid=@item.TestId')">
                        <td class="tbl50 tblheader countclass countclass">
                            @item.Date.ToShortDateString()
                        </td>
                        <td title="" class="tbl200 tblheader">
                            @item.AthleteCount
                        </td>
                        <td title="" class="tbl350 tblheader">
                            @item.Name
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@*<div id="testdata" class="modal fade event-modal" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><b><span id="eventTitle">CREATE NEW TEST</span></b></h4>
                </div>
                <div id="CalenderBody" class="modal-body">
                    <p id="pDetails"></p>
                </div>
                <div class="clearfix"></div>
                <div class="modal-footer">
                    <button type="button" id="ConformBookRoom" class="btn btn-info pull-right">Save</button>
                </div>
            </div>
        </div>
    </div>

    <div id="Add Athlete" class="modal fade event-modal" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><b><span id="eventTitle">ADD NEW ATHLETE TO TEST</span></b></h4>
                </div>
                <div id="AddAthleteBODY" class="modal-body">
                    <p id="pDetails"></p>
                </div>
                <div class="clearfix"></div>
                <div class="modal-footer">
                    <button type="button" id="AddAthletebtn" class="btn btn-info pull-right">Save</button>
                </div>
            </div>
        </div>
    </div>

    <div id="changedataathlete" class="modal fade event-modal" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><b><span id="eventTitle">CHANGE DATAFOR ATHLETE</span></b></h4>
                </div>
                <div id="changedataathleteBODY" class="modal-body">
                    <p id="pDetails"></p>
                </div>
                <div class="clearfix"></div>
                <div class="modal-footer">
                    <button type="button" id="deletedataathleteBTN" class="btn btn-info pull-right">Delete</button>
                    <button type="button" id="changedataathleteBTN" class="btn btn-info pull-right">Save</button>
                </div>
            </div>
        </div>
    </div>

    <div id="Conform" class="modal fade event-modal" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><b><span id="eventTitle">CONFIRM</span></b></h4>
                    <p>Do you want to delete this athlete from test</p>
                </div>
                <div id="ConformBody" class="modal-body">
                    <p id="pDetails"></p>
                </div>
                <div class="clearfix"></div>
                <div class="modal-footer">
                    <button type="button" id="Nobtn" class="btn btn-info pull-right">No</button>
                    <button type="button" id="Yestbtn" class="btn btn-info pull-right">Yes</button>
                </div>
            </div>
        </div>
    </div>*@